# 1. Array Creation Function

In [2]:
import numpy as np

In [3]:
 a = [1,2,3]
a

[1, 2, 3]

In [4]:
type(a)

list

In [5]:
a = np.array(a)

In [6]:
a

array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [8]:
b = np.arange(0,10,2)

In [9]:
b

array([0, 2, 4, 6, 8])

In [10]:
c = np.linspace(0,1,6)
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [11]:
d = np.zeros((2,3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
e = np.ones((3,2))
e

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
f = np.eye(4) # identity mtrix
f

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 2.Array manipulation Functions

In [15]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))
reshaped

array([[1, 2, 3]])

In [16]:
# Flatten an array
f1 = np.array([[1,2],[3,4]])
flattened = np.ravel(f1)
flattened 


array([1, 2, 3, 4])

In [17]:
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
transposed 


array([[1, 3],
       [2, 4]])

In [18]:
# Stack arrays vertically 
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])
stacked

array([[1, 2],
       [3, 4]])

# 3.Mathematical functions 


In [20]:
# Add two arrays

In [21]:
g= np.array([1,2,3,4])
added = np.add(g,2)
added

array([3, 4, 5, 6])

In [22]:
squared = np.power(g,2)
squared

array([ 1,  4,  9, 16], dtype=int32)

In [23]:
sqrt_value = np.sqrt(g)
sqrt_value

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [24]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [25]:
# Dot product of two arrays

a2 = np.array([1,2,3])
dot_Product = np.dot(a2,g)
dot_Product

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [ ]:
print(a1)
print(a2)
print(g)

In [ ]:
print(a)

In [ ]:
a3 = np.array([1,2,3])
dot_product = np.dot(a1,a)
dot_product

# 4.Statistical Function

In [ ]:
s= np.array([1,2,3,4])
mean = np.mean(s)
mean

In [ ]:
# Standard deviation
std_dev = np.std(s)
std_dev

In [ ]:
minimum = np.min(s)
minimum

In [ ]:
maximum = np.max(s)
maximum

# 5.Linear Algebra Function

In [30]:
# create a matrix
matrix = np.array([[1,2],[3,4]])


In [32]:
#Determinant of a matrix
determinant = np.linalg.det(matrix)
print("Determinant of matrix:", determinant)

Determinant of matrix: -2.0000000000000004


In [34]:
#Inverse of a matrix
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n ",inverse)


Inverse of matrix:
  [[-2.   1. ]
 [ 1.5 -0.5]]


# 6.Random Sampling Functions

In [40]:
random_valvs = np.random.rand(3)

In [42]:
random_valvs

array([0.14068561, 0.82589045, 0.45526888])

In [48]:
np.random.seed(0)

random_valvs = np.random.rand(3)
print("Random Values:",random_valvs)

Random Values: [0.5488135  0.71518937 0.60276338]


In [52]:
rand_ints = np.random.randint(0,10,size = 5)
rand_ints

array([2, 4, 7, 6, 8])

In [60]:
np.random.seed(0)

rand_ints = np.random.randint(0,10,size = 5)
rand_ints

array([5, 0, 3, 3, 7])

# 7. Boolean & Logical Functions

In [78]:
logical_test = np.array([True,False,True])
all_true = np.all(logical_test)
all_true

False

In [82]:
any_true = np.any(logical_test)
any_true

True

# 8.Operations

In [85]:
set_a =  np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
intersection = np.intersect1d(set_a,set_b)
intersection

array([3, 4])

In [87]:
union = np.union1d(set_a,set_b)
union

array([1, 2, 3, 4, 5, 6])

# 9.Array Attribute Functions

In [110]:
a = np.array([1,2,3.56])

In [98]:
shape = a.shape # shape of the array

In [100]:
size = a.size


In [102]:
dimensions =  a.ndim

In [114]:
dtype = a.dtype

In [116]:
print(shape)
print(size)
print(dimensions)
print(dtype)

(3,)
3
1
float64


# 10. Other Functions

In [121]:
a = np.array([1,2,3])

In [125]:
copied_array = np.copy(a)

In [127]:
copied_array

array([1, 2, 3])

In [131]:
array_size_in_bytes = a.nbytes

In [133]:
array_size_in_bytes

12

In [135]:
shared = np.shares_memory(a,copied_array)

In [137]:
shared

False