# Loops

In [2]:
i = 1
while i<=5:
    print('Data Science')
    i = i+1

Data Science
Data Science
Data Science
Data Science
Data Science


In [4]:
i = 5
while i>=1:
    print('Data science')
    i = i-1

Data science
Data science
Data science
Data science
Data science


In [6]:
i = 1
while i<=5:
    print('Data Science')
    j = 1
    while j<=4:
        print('Technology')
        j = j+1

        i = i + 1
        print()

Data Science
Technology

Technology

Technology

Technology

Data Science
Technology

Technology

Technology

Technology



In [16]:
i = 1
while i<=5:
    print(' data science ' , end="")
    j = 1
    while j<=4:
        print(' technology ',end = "")
        j = j+1
    i = i+ 1
    print()

 data science  technology  technology  technology  technology 
 data science  technology  technology  technology  technology 
 data science  technology  technology  technology  technology 
 data science  technology  technology  technology  technology 
 data science  technology  technology  technology  technology 


In [18]:
i = 1
while i<=2:
    j = 0
    while j<=2:
        print(i*j,end="")
        j+=1
    print()
    i+=1
    
    


012
024


In [22]:
i = 1
while i<=4:
    j=0
    while j <=3:
        print(i*j,end = "")
        j+=1
    print()
    i+=1
        
    

0123
0246
0369
04812


# For Loop

In [25]:
name = 'nit'

for i in name:
    print(i)

n
i
t


In [27]:
name1 = [1,3.5,'hallo']

for i in name1:
    print(i)

1
3.5
hallo


In [29]:
for i in [2,3,7.8,'hi']:
    print(i)

2
3
7.8
hi


In [31]:
range(5)

range(0, 5)

In [33]:
for i in range(5):
    print(i)

0
1
2
3
4


In [35]:
for i in range(2,5):
    print(i)
    
    

2
3
4


In [37]:
for i in range(1,10,3):
    print(i)

1
4
7


In [39]:
for i in range(1,21):
    print(i)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [41]:
for i in range(1,51):
    if i%5 ==0:
        print(i)

5
10
15
20
25
30
35
40
45
50


In [43]:
for i in range(1,51):
    if i%5!=0:
        print(i)
    

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39
41
42
43
44
46
47
48
49


# Break || Continue || Pass

In [52]:
x = int(input('How many choclets you want:?'))


i=1
while i<=x:
    print('choclet')
    i +=1


How many choclets you want:? 3


choclet
choclet
choclet


In [58]:
available_Chocolate = 5

x= int(input('How many chocolate do you want:?'))
i=1
while i<=x:

    if i>available_Chocolate:
        break
        
    
    print('Chocolate')
    i+=1
print('bye for now')

How many chocolate do you want:? 10


Chocolate
Chocolate
Chocolate
Chocolate
Chocolate
bye for now


In [60]:
available_choclet = 5 # the machine has only 10 candis 

x = int(input('How many choclets you want:?'))

i = 1
while i<=x:
    
    if i>available_choclet: # we stop the execution but which code execution not entire code , i want to come out of while loop 
        print('out of stock')
        break # break is statement | means jump out of the loop
    print('choclet')
    i += 1   
    
print('bye for now')

How many choclets you want:? 90


choclet
choclet
choclet
choclet
choclet
out of stock
bye for now


In [66]:
for i in range(1,11):
    if i == 6:
        break
    print(i)


1
2
3
4
5


In [68]:
for i in range(1,10):
    if i == 3:
        continue
    print(i)

1
2
4
5
6
7
8
9


# Pass statement - pass the code & it will not throw any error 

In [71]:
for i in range(1,11):

SyntaxError: incomplete input (1334445784.py, line 1)

In [73]:
for i in range(1,10):
    pass
    

In [85]:
# print number from 1 to 50 but not print which is divisible by 3 0r 5

for i in range(1,51):
    if i%3==0 or i%5==0:
        continue
    print(i)
print('end')

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49
end


In [93]:
# print odd numbers

for i in range(1,51):
    if i%2== 0:
        continue
    else:
        print(i)
print('End')

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
End


# Printing pattern

In [96]:
for i in range(1,5):
    i = i+1
    print('# # # #')
    

# # # #
# # # #
# # # #
# # # #


In [98]:
for i in range(1,51):
    if i<=5:
        print('# # # # ')


# # # # 
# # # # 
# # # # 
# # # # 
# # # # 


In [100]:
for j in range(4):
    print('#')

#
#
#
#


In [102]:
for j in range(4):
    print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [104]:
for j in range(4):
    print('#', end = " ")

# # # # 

In [106]:
for j in range(4):
    print('#', end=" ")

for j in range(4):
    print('#', end=" ")

# # # # # # # # 

In [108]:
for j in range(4):
    print('#', end=" ")
    
print()
    
for j in range(4):
    print('#', end=" ")

# # # # 
# # # # 

In [110]:
for j in range(4):
    print('#', end="  ")
    
print()

for j in range(4):
    print('#', end="  ")

print()

for j in range(4):
    print('#', end="  ")
    
print()

for j in range(4):
    print('#', end="  ")

#  #  #  #  
#  #  #  #  
#  #  #  #  
#  #  #  #  

In [116]:
for i in range(4):
    for j in range(4):
        print('#', end="  ")
    print()

#  #  #  #  
#  #  #  #  
#  #  #  #  
#  #  #  #  


In [118]:
for i in range(4):
    for j in range(i+1):
        print('#', end = " ")
    print()

# 
# # 
# # # 
# # # # 


In [122]:
for i in range(1,5):
    print('# '* i)

# 
# # 
# # # 
# # # # 


In [124]:
for i in range(1,5):
    for j in range(4):
        if i>j:
            print("#",end=" ")
    print()

# 
# # 
# # # 
# # # # 


In [126]:
list(range(5))

[0, 1, 2, 3, 4]

In [128]:
for i in range(4):
    for j in range(i):
        print('#', end="  ")
    print()


#  
#  #  
#  #  #  


In [130]:
for i in range(4):
    for j in range(i+1):
        print('#', end="  ")
    print()

#  
#  #  
#  #  #  
#  #  #  #  


In [132]:
for i in range(4):
    for j in range(4-i):
        print('#', end="  ")
    print()

#  #  #  #  
#  #  #  
#  #  
#  


In [136]:
for i in range(1,5):
    print("#  "*(5-i))

#  #  #  #  
#  #  #  
#  #  
#  


#  For else

In [141]:
# print number from 1 to 20 & do not print number which is divisible by 5


In [143]:
nums = [12,15,18,21,26]

for num in nums:
    if num % 5 == 0:
        print(num) 

15


In [145]:
nums = [12,14,18,21,25,30,35]

for num in nums:
    if num % 5 == 0:
        print(num)  

25
30
35


In [147]:
nums = [12,14,18,21,25,20]

for num in nums:
    if num % 5 == 0:
        print(num)  

25
20


In [149]:
nums = [12,14,18,21,20,25]

for num in nums:
    if num % 5 == 0:
        print(num)  
        break

20


In [151]:
nums = [10,14,18,21,5,10]

for num in nums:
    if num % 5 == 0:
        print(num)  
        break #it will print only 1 number then it break    

10


In [153]:
nums = [7,14,18,21,23,27] 

for num in nums:
    if num % 5 == 0:
        print(num)  
        break
    else:
        print('Number Not Found')

Number Not Found
Number Not Found
Number Not Found
Number Not Found
Number Not Found
Number Not Found


In [157]:
nums = [7,14] 
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
    else:
        print('Number Not Found')      

Number Not Found
Number Not Found


In [159]:
nums = [10,14,18,21,20,27,30] 
for num in nums:
    if num % 5 == 0:
        print(num)  
        #break
else:
        print('Not Found')

10
20
30
Not Found


In [161]:
nums = [7,14,18,21,23,27] #hear there is no number which is divisible by 5 we got output as blank

for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Number Not Found') # hear else we dont write in if block but we can write in for block only

Number Not Found


In [169]:
nums = [10,14,18,21,20,27] #hear there is no number which is divisible by 5 we got output as blank
for num in nums:
    if num % 5 == 0:
        print(num)  
        break
else:
        print('Not Found')

10


In [185]:
# prime number

num = 14

for i in range(2,num):
    if num % i == 0:
        print('Not prime number')
        break
    else:
        print('Prime Number')

Not prime number


In [183]:
num = 13 
for i in range(2,num):
    if num % i == 0:
        print('Not a prime number')
        break
    else:
        print('Prime number')
        break
        

Prime number


# Array in python

In [190]:
from array import *
arr = array('i',[])

n = int(input('Enter the length of the array'))

for i in range(n):
    x = int(input('Enter the next value '))
    arr.append(x)

print(arr)

Enter the length of the array 2
Enter the next value  1
Enter the next value  2


array('i', [1, 2])


In [192]:
from array import *
arr = array('i',[])
n = int(input('Enter the length of the array'))

for i in range(n):
    x = int(input('Enter the value:'))
    arr.append(x)
print(arr)

Enter the length of the array 3
Enter the value: 1
Enter the value: 2
Enter the value: 3


array('i', [1, 2, 3])


In [194]:
# By using numpy create array

from numpy import*
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [196]:
print(arr.dtype)

int32


In [198]:
arr2 = array([1,2,3,4,5],float)
arr2

array([1., 2., 3., 4., 5.])

In [202]:
arr3 = array([1,2,3,4.6,5.8],int)
arr3

array([1, 2, 3, 4, 5])

In [208]:
import numpy as np


In [212]:
arr4 =np.linspace(0,16,10)
arr4

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [214]:
arr5 = np.arange(0,10,2)

In [216]:
arr5

array([0, 2, 4, 6, 8])

In [218]:
arr6 = np.zeros(5)
arr6

array([0., 0., 0., 0., 0.])

In [220]:
arr7 = np.ones(2)
arr7

array([1., 1.])

In [ ]:
import tkinter as tk

def on_buttton_click():
    label.config(text="Button clicked!")

root = tk.Tk()
root.title('Simple Tkinter app')

label = tk.Label(root,text="Hello,Tkinter!")
label.pack(pady=20)

button = tk.Button(root,text = "Click Me",command=on_buttton_click)
button.pack(pady=20)

root.mainloop()

In [ ]:
import tkinter as tk
from tkinter import messagebox

# Function to be called when the button is clicked
def on_button_click():
    user_input = entry.get()
    messagebox.showinfo("Information", f"You entered: {user_input}")

# Create the main application window
root = tk.Tk()
root.title("Simple Tkinter App")

# Create a label widget
label = tk.Label(root, text="Enter something:")
label.pack(pady=10)

# Create a text entry widget
entry = tk.Entry(root, width=30)
entry.pack(pady=10)

# Create a button widget
button = tk.Button(root, text="Submit", command=on_button_click)
button.pack(pady=10)

# Run the application
root.mainloop()