# 04/02/2025

In [2]:
import numpy as np

In [3]:
np.random.randint(20,30,10)

array([20, 20, 22, 20, 28, 27, 26, 22, 22, 21])

In [4]:
np.random.randint(10,40,(10,10))

array([[23, 34, 11, 33, 32, 37, 12, 29, 30, 29],
       [28, 17, 11, 10, 37, 39, 35, 23, 29, 19],
       [14, 30, 18, 28, 10, 30, 33, 27, 12, 20],
       [28, 36, 11, 16, 20, 22, 10, 12, 27, 11],
       [36, 24, 24, 39, 39, 30, 31, 15, 30, 31],
       [24, 34, 16, 28, 30, 29, 11, 38, 14, 25],
       [24, 23, 26, 23, 29, 37, 29, 31, 14, 17],
       [37, 14, 11, 33, 33, 23, 39, 24, 12, 39],
       [21, 14, 38, 19, 34, 20, 31, 21, 25, 34],
       [34, 37, 11, 12, 10, 30, 28, 16, 17, 20]])

In [5]:
np.random.randint(1,100,(12,12))

array([[14, 85, 54, 31, 72, 67, 12, 52, 91, 14, 91, 26],
       [54, 18, 57, 79, 12, 66, 56, 77, 34, 12, 30, 90],
       [80, 24, 55, 37, 42, 47, 39, 78, 81, 47, 56, 17],
       [58, 49, 13, 71, 51, 20, 96, 13, 84, 44, 72, 83],
       [37, 62, 90, 71, 54, 80, 41, 72, 29, 97, 13, 40],
       [33, 58, 77, 85, 79, 68, 31, 25, 96, 27, 58, 38],
       [53, 13, 35, 64, 98,  4, 77, 36, 21, 93, 52,  2],
       [ 9, 88, 46, 65, 65, 73, 76, 90, 97, 50, 50, 75],
       [56, 94, 85, 42, 50, 83, 61, 75, 90, 55,  6, 88],
       [83, 56,  2, 78, 68,  5, 53, 40, 28,  3, 94, 73],
       [87, 61, 85, 80, 63, 18, 89, 10, 77, 81, 57, 58],
       [30, 47,  9, 24, 70,  3, 25,  7, 93, 76, 11, 67]])

In [6]:
np.random.randint(2,5,3)

array([3, 2, 3])

In [7]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [9]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [10]:
 b = np.random.randint(10,20,(5,4))
b

array([[10, 19, 15, 12],
       [19, 10, 12, 10],
       [16, 16, 15, 16],
       [16, 18, 13, 15],
       [12, 15, 12, 16]])

In [11]:
type(b)

numpy.ndarray

In [12]:
b[:]

array([[10, 19, 15, 12],
       [19, 10, 12, 10],
       [16, 16, 15, 16],
       [16, 18, 13, 15],
       [12, 15, 12, 16]])

In [13]:
b[1:3]

array([[19, 10, 12, 10],
       [16, 16, 15, 16]])

In [14]:
b[:,1:3]

array([[19, 15],
       [10, 12],
       [16, 15],
       [18, 13],
       [15, 12]])

In [15]:
b[1,2]

12

In [16]:
b

array([[10, 19, 15, 12],
       [19, 10, 12, 10],
       [16, 16, 15, 16],
       [16, 18, 13, 15],
       [12, 15, 12, 16]])

In [17]:
b[1,-1]

10

In [18]:
b[2:3]

array([[16, 16, 15, 16]])

In [19]:
b[0:-2]

array([[10, 19, 15, 12],
       [19, 10, 12, 10],
       [16, 16, 15, 16]])

In [20]:
b[-5,-3]

19

# slicing in matrix

In [22]:
b = np.random.randint(10,20,(5,4))
b

array([[16, 17, 14, 15],
       [19, 19, 10, 16],
       [13, 13, 19, 10],
       [19, 18, 18, 16],
       [18, 12, 15, 16]])

In [23]:
type(b)

numpy.ndarray

In [24]:
b[:]

array([[16, 17, 14, 15],
       [19, 19, 10, 16],
       [13, 13, 19, 10],
       [19, 18, 18, 16],
       [18, 12, 15, 16]])

# Operations

In [34]:
a = np.random.randint(10,20,10)
a

array([12, 18, 12, 10, 13, 16, 13, 16, 12, 15])

In [36]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[71, 24, 12, 89,  0, 57, 40, 38, 69, 52],
       [33,  8,  3, 76,  4, 37, 27, 51, 20, 38],
       [83, 97, 23, 95, 54, 30, 76, 89, 26,  8],
       [11,  6,  9, 45, 50, 46, 34, 87, 80, 95],
       [14, 31,  0, 59, 95, 64, 26, 81, 89,  8],
       [50, 37, 56, 94, 29, 99, 64, 87, 26, 70],
       [ 3, 23, 53, 87, 50, 56, 22, 86, 80, 93],
       [79, 46, 12, 80, 67, 98, 82, 95, 83, 71],
       [97, 86, 68, 38, 67, 52,  3, 32, 17, 85],
       [44, 48, 27, 58, 30, 58, 29, 54, 43, 68]])

In [38]:
arr2[:]

array([[71, 24, 12, 89,  0, 57, 40, 38, 69, 52],
       [33,  8,  3, 76,  4, 37, 27, 51, 20, 38],
       [83, 97, 23, 95, 54, 30, 76, 89, 26,  8],
       [11,  6,  9, 45, 50, 46, 34, 87, 80, 95],
       [14, 31,  0, 59, 95, 64, 26, 81, 89,  8],
       [50, 37, 56, 94, 29, 99, 64, 87, 26, 70],
       [ 3, 23, 53, 87, 50, 56, 22, 86, 80, 93],
       [79, 46, 12, 80, 67, 98, 82, 95, 83, 71],
       [97, 86, 68, 38, 67, 52,  3, 32, 17, 85],
       [44, 48, 27, 58, 30, 58, 29, 54, 43, 68]])

In [40]:
arr

NameError: name 'arr' is not defined

In [42]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [44]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [46]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [48]:
arr[:4]

array([0, 1, 2, 3])

In [50]:
arr2

array([[71, 24, 12, 89,  0, 57, 40, 38, 69, 52],
       [33,  8,  3, 76,  4, 37, 27, 51, 20, 38],
       [83, 97, 23, 95, 54, 30, 76, 89, 26,  8],
       [11,  6,  9, 45, 50, 46, 34, 87, 80, 95],
       [14, 31,  0, 59, 95, 64, 26, 81, 89,  8],
       [50, 37, 56, 94, 29, 99, 64, 87, 26, 70],
       [ 3, 23, 53, 87, 50, 56, 22, 86, 80, 93],
       [79, 46, 12, 80, 67, 98, 82, 95, 83, 71],
       [97, 86, 68, 38, 67, 52,  3, 32, 17, 85],
       [44, 48, 27, 58, 30, 58, 29, 54, 43, 68]])

In [52]:
arr2[0:5]

array([[71, 24, 12, 89,  0, 57, 40, 38, 69, 52],
       [33,  8,  3, 76,  4, 37, 27, 51, 20, 38],
       [83, 97, 23, 95, 54, 30, 76, 89, 26,  8],
       [11,  6,  9, 45, 50, 46, 34, 87, 80, 95],
       [14, 31,  0, 59, 95, 64, 26, 81, 89,  8]])

In [54]:
arr2[-5,5]

99

In [56]:
arr2

array([[71, 24, 12, 89,  0, 57, 40, 38, 69, 52],
       [33,  8,  3, 76,  4, 37, 27, 51, 20, 38],
       [83, 97, 23, 95, 54, 30, 76, 89, 26,  8],
       [11,  6,  9, 45, 50, 46, 34, 87, 80, 95],
       [14, 31,  0, 59, 95, 64, 26, 81, 89,  8],
       [50, 37, 56, 94, 29, 99, 64, 87, 26, 70],
       [ 3, 23, 53, 87, 50, 56, 22, 86, 80, 93],
       [79, 46, 12, 80, 67, 98, 82, 95, 83, 71],
       [97, 86, 68, 38, 67, 52,  3, 32, 17, 85],
       [44, 48, 27, 58, 30, 58, 29, 54, 43, 68]])

In [58]:
arr2[-5,-5]

99

In [60]:
arr2[-1,-2]

43

In [62]:
arr2

array([[71, 24, 12, 89,  0, 57, 40, 38, 69, 52],
       [33,  8,  3, 76,  4, 37, 27, 51, 20, 38],
       [83, 97, 23, 95, 54, 30, 76, 89, 26,  8],
       [11,  6,  9, 45, 50, 46, 34, 87, 80, 95],
       [14, 31,  0, 59, 95, 64, 26, 81, 89,  8],
       [50, 37, 56, 94, 29, 99, 64, 87, 26, 70],
       [ 3, 23, 53, 87, 50, 56, 22, 86, 80, 93],
       [79, 46, 12, 80, 67, 98, 82, 95, 83, 71],
       [97, 86, 68, 38, 67, 52,  3, 32, 17, 85],
       [44, 48, 27, 58, 30, 58, 29, 54, 43, 68]])

In [64]:
arr2[::-1]

array([[44, 48, 27, 58, 30, 58, 29, 54, 43, 68],
       [97, 86, 68, 38, 67, 52,  3, 32, 17, 85],
       [79, 46, 12, 80, 67, 98, 82, 95, 83, 71],
       [ 3, 23, 53, 87, 50, 56, 22, 86, 80, 93],
       [50, 37, 56, 94, 29, 99, 64, 87, 26, 70],
       [14, 31,  0, 59, 95, 64, 26, 81, 89,  8],
       [11,  6,  9, 45, 50, 46, 34, 87, 80, 95],
       [83, 97, 23, 95, 54, 30, 76, 89, 26,  8],
       [33,  8,  3, 76,  4, 37, 27, 51, 20, 38],
       [71, 24, 12, 89,  0, 57, 40, 38, 69, 52]])

In [68]:
arr2

array([[71, 24, 12, 89,  0, 57, 40, 38, 69, 52],
       [33,  8,  3, 76,  4, 37, 27, 51, 20, 38],
       [83, 97, 23, 95, 54, 30, 76, 89, 26,  8],
       [11,  6,  9, 45, 50, 46, 34, 87, 80, 95],
       [14, 31,  0, 59, 95, 64, 26, 81, 89,  8],
       [50, 37, 56, 94, 29, 99, 64, 87, 26, 70],
       [ 3, 23, 53, 87, 50, 56, 22, 86, 80, 93],
       [79, 46, 12, 80, 67, 98, 82, 95, 83, 71],
       [97, 86, 68, 38, 67, 52,  3, 32, 17, 85],
       [44, 48, 27, 58, 30, 58, 29, 54, 43, 68]])

In [66]:
arr2[::-2]

array([[44, 48, 27, 58, 30, 58, 29, 54, 43, 68],
       [79, 46, 12, 80, 67, 98, 82, 95, 83, 71],
       [50, 37, 56, 94, 29, 99, 64, 87, 26, 70],
       [11,  6,  9, 45, 50, 46, 34, 87, 80, 95],
       [33,  8,  3, 76,  4, 37, 27, 51, 20, 38]])

In [70]:
arr2[::-3]

array([[44, 48, 27, 58, 30, 58, 29, 54, 43, 68],
       [ 3, 23, 53, 87, 50, 56, 22, 86, 80, 93],
       [11,  6,  9, 45, 50, 46, 34, 87, 80, 95],
       [71, 24, 12, 89,  0, 57, 40, 38, 69, 52]])

In [72]:
arr2

array([[71, 24, 12, 89,  0, 57, 40, 38, 69, 52],
       [33,  8,  3, 76,  4, 37, 27, 51, 20, 38],
       [83, 97, 23, 95, 54, 30, 76, 89, 26,  8],
       [11,  6,  9, 45, 50, 46, 34, 87, 80, 95],
       [14, 31,  0, 59, 95, 64, 26, 81, 89,  8],
       [50, 37, 56, 94, 29, 99, 64, 87, 26, 70],
       [ 3, 23, 53, 87, 50, 56, 22, 86, 80, 93],
       [79, 46, 12, 80, 67, 98, 82, 95, 83, 71],
       [97, 86, 68, 38, 67, 52,  3, 32, 17, 85],
       [44, 48, 27, 58, 30, 58, 29, 54, 43, 68]])

In [74]:
arr2[:-3]

array([[71, 24, 12, 89,  0, 57, 40, 38, 69, 52],
       [33,  8,  3, 76,  4, 37, 27, 51, 20, 38],
       [83, 97, 23, 95, 54, 30, 76, 89, 26,  8],
       [11,  6,  9, 45, 50, 46, 34, 87, 80, 95],
       [14, 31,  0, 59, 95, 64, 26, 81, 89,  8],
       [50, 37, 56, 94, 29, 99, 64, 87, 26, 70],
       [ 3, 23, 53, 87, 50, 56, 22, 86, 80, 93]])

In [76]:
arr

array([0, 1, 2, 3, 4, 5])

In [78]:
arr.max()

5

In [80]:
arr.min()

0

In [82]:
arr.mean()

2.5

In [84]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [86]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

In [88]:
arr

array([0, 1, 2, 3, 4, 5])

In [90]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [92]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [102]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [108]:
arr.reshape(2,3,order = 'C')

array([[0, 1, 2],
       [3, 4, 5]])

In [110]:
arr.reshape(2,3,order = 'F')

array([[0, 2, 4],
       [1, 3, 5]])

In [112]:
arr.reshape(2,3,order = 'A')

array([[0, 1, 2],
       [3, 4, 5]])

# Indexing

In [119]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [121]:
row = 4
col = 5

In [127]:
col

5

In [129]:
row

4

In [131]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [133]:
mat[row,col]

45

In [138]:
mat[4,5]
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [140]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [142]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [144]:
mat[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [146]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [148]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [150]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [152]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [154]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [156]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [158]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [160]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [162]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [164]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [166]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [168]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [170]:
mat[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [172]:
mat[1,4]

14

In [174]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [176]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [178]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [183]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [185]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [187]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [189]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [191]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [193]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [195]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [197]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [199]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [207]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [203]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [205]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [209]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [211]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [213]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [215]:
mat[0,1]

1

In [217]:
mat[1,6]

16

In [219]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [221]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [223]:
mat[1:2,2:4]

array([[12, 13]])

# Masking

In [226]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [228]:
mat[mat < 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [232]:
mat[mat <= 50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [234]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [236]:
mat[mat == 50]

array([50])

In [238]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [242]:
a1 = mat[mat < 50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [244]:
a2 = mat[mat > 50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Python program to generate OTP

In [253]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp


otp_length = 4
otp = generate_otp(otp_length)
print(f"Your OTP is : {otp}")

Your OTP is : 3334
